### ISSUE TITLE
Note component

### ISSUE THREAD

**Issue by dwhieb** [digitallinguistics/app#219]
Create a Note component, which allows the user to edit/delete a note.

# Notes

* Do not emit events. Event delegation will happen for all notes in the parent view.

# Todo

- [x] render note text preview
- [x] ~~render note language preview (string = 'English')~~
- [x] render note source preview (string)
- [x] render date created
- [x] render date modified
- [x] render note text editor
- [x] ~~render note language editor~~
- [x] render note source editor
- [x] render delete button
- [x] render edit button
- [x] render cancel button
- [x] render save button
- [x] render with editor hidden by default
- [x] styling
- [x] display editor when edit button is clicked
- [x] hide edit button after edit button is clicked
- [x] hide editor when cancel button is clicked
- [x] hide editor when save button is clicked
- [x] display editor when preview text is clicked
- [x] revert preview when cancel button is clicked
- [x] revert source preview when cancel button is clicked
- [x] update preview when save button is clicked
- [x] update source when save button is clicked
- [x] update date modified when save button is clicked

# Inspiration

- Evernote mobile
- GitHub comments
