### ISSUE TITLE
Tagger

### ISSUE THREAD

**Issue by dwhieb** [digitallinguistics/app#267]
### Problem

The user should be able to apply tags to a text (not the entire corpus) in a rapid fashion.

### Notes

* Do _not_ implement a concordance search + tagging interface. This belongs in the Search page instead.
* The interface should be entirely - and quickly - navigable with a keyboard.

### MVP

- [x] Texts List (#289)
- [x] Text Tagger (#297)
- [x] Text Tagger: Title (#304)
- [x] Text Tagger: Text (#305)
- [x] Tag (#319)
- [x] Tags List (#321)
- [x] Text Tagger: display word-level tags (#336)
- [x] Text Tagger: navigate by utterance (#339)
- [x] Text Tagger: navigate by word (#341)
- [x] Text Tagger: type to tag (#343)
- [x] Text Tagger: click to delete tag (#345)
- [x] Text Tagger: click to tag (#355)
- [x] Database: export data (#372)
- [x] Settings: export data (#374)
- [x] Settings: export data on exit (#286)
- [x] Nav: make collapsible (#125)

**Comment by dwhieb** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [👨🏼‍💻 [app] Tagger](https://trello.com/c/WiXVVClM/678-%F0%9F%91%A8%F0%9F%8F%BC%F0%9F%92%BB-app-tagger)
