### ISSUE TITLE
Languages List

### ISSUE THREAD

**Issue by dwhieb** [digitallinguistics/app#91]
The user should be able to see a list of languages on the Languages Page. Each language should display its name in the default orthography. Clicking on a language should load the editor interface for that language.

**Features**
- [x] display list of languages
- [x] ~~user can add a language~~ (#165)

**Integration Tests**
- [x] clicking a language updates the selected value of the Language Dropdown (#200)
- [x] clicking a language renders the Language Editor for that language (#201)
